amcl:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.1
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 12.0
    laser_min_range: 0.3
    laser_model_type: "likelihood_field"
    max_beams: 180
    max_particles: 5000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.02
    pf_z: 0.95
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 3
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.1
    tf_broadcast: true
    transform_tolerance: 1.0
    tf_buffer_duration: 30.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.9
    z_max: 0.05
    z_rand: 0.05
    z_short: 0.0
    scan_topic: /scan
    map_subscribe_transient_local: True
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 20
    default_server_timeout: 60
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_only_if_path_becomes_invalid.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_smoother_selector_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node

controller_server:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    controller_frequency: 10.0
    failure_tolerance: 2.0
    min_x_velocity_threshold: 0.02
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.05
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    current_goal_checker: "goal_checker"
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 30.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.10
      stateful: True

    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "dwb_core::DWBLocalPlanner"
      angular_dist_threshold: 0.785 
      forward_sampling_distance: 0.5  
      rotate_to_heading_angular_vel: 0.4
      max_angular_accel: 1.2
      simulate_ahead_time: 1.0      
      debug_trajectory_details: False
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.43
      max_vel_y: 0.0
      max_vel_theta: 1.5
      min_vel_theta: -1.5
      min_speed_xy: 0.0
      max_speed_xy: 0.43
      min_speed_theta: 0.02
      acc_lim_x: 0.20
      acc_lim_y: 0.0
      acc_lim_theta: 1.5
      decel_lim_x: -1.5
      decel_lim_y: 0.0
      decel_lim_theta: -1.5

      vx_samples: 20           
      vy_samples: 0
      vtheta_samples: 24       
      sim_time: 1.0            
      linear_granularity: 0.08
      angular_granularity: 0.04
      transform_tolerance: 0.3
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.10
      trans_stopped_velocity: 0.05
      theta_stopped_velocity: 0.10
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["BaseObstacle", "ObstacleFootprint", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "RotateToGoal"]
      BaseObstacle.scale: 0.10      
      ObstacleFootprint.scale: 0.08 
      PathAlign.scale: 48.0
      GoalAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.forward_point_distance: 0.1

      PathDist.scale: 64.0
      GoalDist.scale: 64.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 10.0
      RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.5
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.05
      robot_radius: 0.18
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.5     
        inflation_radius: 0.45      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_persistence: 0.0
        combination_method: 1
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.30
          obstacle_max_range: 5.5
          obstacle_min_range: 0.30
      always_send_full_costmap: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      transform_tolerance: 0.5
      robot_radius: 0.18
      resolution: 0.05          
      track_unknown_space: true
      rolling_window: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: True
        allow_unknown: false   
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.30
          obstacle_max_range: 5.5
          obstacle_min_range: 0.30
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.5  
        inflation_radius: 0.55    
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: True
    use_bond: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"  
      downsample_costmap: false
      downsampling_factor: 1
      tolerance: 0.25
      allow_unknown: false         
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 2.0
      cost_travel_multiplier: 2.0   
      use_final_approach_orientation: false
      smoother:                     
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2

smoother_server:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 2000        
      do_refinement: True
      refinement_num: 3    
      w_smooth: 0.4        
      w_data: 0.2          

behavior_server:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading",
                       "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.3
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.5
    min_rotational_vel: 0.10
    rotational_vel_error_allowable: 0.1

waypoint_follower:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: True
    use_bond: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.43, 0.0, 1.5]
    min_velocity: [-0.43, 0.0, -1.5]
    max_accel: [0.20, 0.0, 1.5]
    odom_topic: "/odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - map_server
      - amcl

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - planner_server
      - smoother_server
      - controller_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - velocity_smoother
