c:
  pose:
    x: 0.0
    y: 0.5
    yaw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
a:
  pose:
    x: 0.0
    y: 1.0
    yaw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
b:
  pose:
    x: 0.0
    y: 1.5
    yaw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0